use serde::{Deserialize, Serialize};

/// The config file written by the Tauri desktop app and read by the server binary.
/// Contains everything the server needs — one file, no database.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerConfig {
    /// Workflow name — displayed on status page.
    pub workflow_name: String,

    /// Full workflow JSON (the same format saved by the desktop app).
    pub workflow_json: String,

    /// Port for the status HTTP server.
    pub status_port: u16,

    /// ISO-8601 timestamp of when this package was generated.
    pub exported_at: String,

    /// Credential IDs referenced by the workflow, mapped to the env var name
    /// the user must set. e.g. {"openai-prod": "FLOWO_CRED_OPENAI_PROD"}
    pub credential_env_vars: std::collections::HashMap<String, String>,

    /// Optional secret token required to trigger POST /api/run on the status page.
    /// Generated by the desktop app at export time.
    /// Since Flowo 0.3: contains an argon2id PHC string (~97 chars, starts with "$argon2").
    /// Since Flowo 0.2: contained the BLAKE3 hex-digest of the raw secret (64 chars) — still supported for backward compat.
    /// The raw secret is shown once in the desktop UI and never written to disk.
    /// Set to None to disable the trigger button entirely (read-only status page).
    #[serde(default)]
    pub run_secret: Option<String>,
}

impl ServerConfig {
    pub fn from_file(path: &std::path::Path) -> Result<Self, String> {
        let content = std::fs::read_to_string(path)
            .map_err(|e| format!("Cannot read config file '{}': {}", path.display(), e))?;
        serde_json::from_str(&content)
            .map_err(|e| format!("Config file is not valid JSON: {}", e))
    }
}
