//! Flowo Server — two modes, one binary.
//!
//! MODE 1: Single-workflow daemon (--serve)
//!   Reads flowo-server.json generated by the desktop app.
//!   Runs one workflow on its schedule, serves a status page.
//!   This is what the Export for Server panel produces.
//!
//!   flowo-server serve
//!   flowo-server serve --config /path/to/flowo-server.json --port 7700
//!
//! MODE 2: Multi-workflow REST API (--api)
//!   Manages many workflows via HTTP API + bearer token auth.
//!   Useful for power users running multiple workflows on one machine.
//!
//!   flowo-server api --token mytoken --port 7700
//!   FLOWO_TOKEN=mytoken flowo-server api
//!
//! CONTROL COMMANDS (for MODE 2):
//!   flowo-server list                           — list all scheduled jobs
//!   flowo-server stop   <workflow-id-or-name>   — stop a workflow
//!   flowo-server start  <workflow-id-or-name>   — start a workflow
//!   flowo-server restart <workflow-id-or-name>  — restart a workflow

mod api_server;
mod config;
mod env_credentials;
mod event_bridge;
mod log_buffer;
mod status_server;
mod token_store;
mod util;

use std::path::PathBuf;
use std::sync::{Arc, RwLock};

use clap::{Parser, Subcommand};
use flowo_engine::{
    db::WorkflowDb,
    model::Workflow,
    node::NodeRegistry,
    nodes::register_builtins,
    scheduler::{extract_trigger, SchedulerDaemon, SchedulerDb},
};

use config::ServerConfig;
use env_credentials::EnvCredentialResolver;
use event_bridge::{EventBridge, RunState};
use log_buffer::LogBuffer;

#[derive(Parser)]
#[command(
    name    = "flowo-server",
    version = "0.1.0",
    about   = "Flowo headless workflow server",
    long_about = None
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Run a single exported workflow (generated by File → Export for Server).
    Serve {
        /// Path to flowo-server.json
        #[arg(long, default_value = "flowo-server.json")]
        config: PathBuf,

        /// Override the status page port from flowo-server.json
        #[arg(long)]
        port: Option<u16>,

        /// Interface to bind the status page server to.
        /// Default is 127.0.0.1 (localhost only). Use 0.0.0.0 to expose publicly.
        #[arg(long, default_value = "127.0.0.1")]
        bind: String,

        /// Number of reverse-proxy hops to trust when reading X-Forwarded-For.
        /// Set to the number of proxies between the internet and this server.
        /// Default 0 = use TCP source IP directly.
        #[arg(long, env = "FLOWO_TRUSTED_PROXY_COUNT", default_value_t = 0)]
        trusted_proxy_count: usize,
    },

    /// Run the multi-workflow REST API server.
    Api {
        /// Bearer token for API authentication.
        /// Generates a random token on first run if not set.
        #[arg(long, env = "FLOWO_TOKEN")]
        token: Option<String>,

        /// Port to listen on
        #[arg(long, env = "FLOWO_PORT", default_value = "7700")]
        port: u16,

        /// Data directory for the SQLite database and key file
        #[arg(long, env = "FLOWO_DATA_DIR", default_value = "~/.flowo-server")]
        data_dir: String,

        /// Additional origins allowed to call the API (comma-separated).
        /// Localhost origins are always allowed.
        /// Example: --allow-origin https://myapp.example.com
        #[arg(long = "allow-origin", value_delimiter = ',')]
        allow_origins: Vec<String>,

        /// Environment variable names that workflows may read via {{$env.VAR}}.
        /// Disabled by default — $env resolves to "" unless listed here.
        /// Example: --allow-env-vars HOME,APP_ENV
        #[arg(long = "allow-env-vars", value_delimiter = ',')]
        allow_env_vars: Vec<String>,

        /// Interface to bind to.
        /// Default is 127.0.0.1 (localhost only). Use 0.0.0.0 to expose publicly.
        #[arg(long, default_value = "127.0.0.1")]
        bind: String,

        /// Restrict File nodes to this directory tree (recommended in production).
        /// When set, File nodes cannot read or write paths outside this directory.
        #[arg(long)]
        file_sandbox_dir: Option<std::path::PathBuf>,

        /// Number of reverse-proxy hops to trust when reading X-Forwarded-For.
        /// Set this to the number of proxies (nginx, Caddy, load balancer) between
        /// the internet and this server. Default 0 = use TCP source IP directly.
        /// Example: --trusted-proxy-count 1 when behind a single nginx.
        #[arg(long, env = "FLOWO_TRUSTED_PROXY_COUNT", default_value_t = 0)]
        trusted_proxy_count: usize,

        /// Disable Shell Command nodes. Disabled by default — Shell Command nodes
        /// execute arbitrary OS commands and are off unless explicitly opted in.
        /// To allow shell execution: --disable-shell=false
        #[arg(
            long,
            num_args(0..=1),
            action = clap::ArgAction::Set,
            default_value_t = true,
            default_missing_value = "true",
        )]
        disable_shell: bool,

        /// Disable Code (JS) nodes. Disabled by default — Code nodes spawn a Node.js
        /// process and are off unless explicitly opted in.
        /// To allow code execution: --disable-code=false
        #[arg(
            long,
            num_args(0..=1),
            action = clap::ArgAction::Set,
            default_value_t = true,
            default_missing_value = "true",
        )]
        disable_code: bool,

        /// Use the OS keychain (macOS Keychain, Windows Credential Manager,
        /// Linux SecretService) to store the encryption key instead of a
        /// plain file. Recommended on desktop-adjacent servers.
        /// If the keychain is unavailable the server falls back to the file
        /// automatically with a warning.
        #[arg(long, default_value_t = false)]
        keychain: bool,

        /// Enable parallel execution of independent workflow branches.
        /// When set, nodes whose upstream dependencies have all completed run
        /// concurrently instead of sequentially. Off by default — the sequential
        /// path is unchanged unless this flag is explicitly passed.
        #[arg(long, default_value_t = false)]
        parallel_execution: bool,

        /// Maximum number of nodes executing simultaneously in parallel mode.
        /// Ignored when --parallel-execution is not set. Default: 8.
        #[arg(long, default_value_t = 8)]
        max_concurrent_nodes: usize,
    },

    /// List all scheduled workflows (API mode only).
    List {
        #[arg(long, default_value = "http://localhost:7700")]
        server: String,

        #[arg(long, env = "FLOWO_TOKEN")]
        token: String,
    },

    /// Stop a running workflow (API mode only).
    Stop {
        /// Workflow ID or name (partial match accepted)
        workflow: String,

        #[arg(long, default_value = "http://localhost:7700")]
        server: String,

        #[arg(long, env = "FLOWO_TOKEN")]
        token: String,
    },

    /// Start a stopped workflow (API mode only).
    Start {
        /// Workflow ID or name (partial match accepted)
        workflow: String,

        #[arg(long, default_value = "http://localhost:7700")]
        server: String,

        #[arg(long, env = "FLOWO_TOKEN")]
        token: String,
    },

    /// Restart a workflow — stop then start (API mode only).
    Restart {
        /// Workflow ID or name (partial match accepted)
        workflow: String,

        #[arg(long, default_value = "http://localhost:7700")]
        server: String,

        #[arg(long, env = "FLOWO_TOKEN")]
        token: String,
    },

    /// Print the status of all scheduled workflows (API mode only).
    Status {
        #[arg(long, default_value = "http://localhost:7700")]
        server: String,

        #[arg(long, env = "FLOWO_TOKEN")]
        token: String,
    },

    /// Manage API tokens (API mode only).
    Tokens {
        #[command(subcommand)]
        action: TokenAction,
    },
}

#[derive(Subcommand)]
enum TokenAction {
    /// List all tokens (active and revoked).
    List {
        #[arg(long, default_value = "http://localhost:7700")]
        server: String,

        #[arg(long, env = "FLOWO_TOKEN")]
        token: String,
    },

    /// Create a new token.
    Create {
        /// Human-readable label for the token (e.g. "ci", "dashboard").
        #[arg(long)]
        label: String,

        /// Comma-separated scopes: read, write, admin.
        #[arg(long = "scopes", value_delimiter = ',', default_value = "read,write")]
        scopes: Vec<String>,

        #[arg(long, default_value = "http://localhost:7700")]
        server: String,

        #[arg(long, env = "FLOWO_TOKEN")]
        token: String,
    },

    /// Revoke a token by its token_id.
    Revoke {
        /// Token ID (from `tokens list`).
        token_id: String,

        #[arg(long, default_value = "http://localhost:7700")]
        server: String,

        #[arg(long, env = "FLOWO_TOKEN")]
        token: String,
    },
}

#[tokio::main]
async fn main() {
    let cli = Cli::parse();

    match cli.command {
        Command::Serve { config, port, bind, trusted_proxy_count } => serve_mode(config, port, bind, trusted_proxy_count).await,
        Command::Api { token, port, data_dir, allow_origins, allow_env_vars, bind, file_sandbox_dir, trusted_proxy_count, disable_shell, disable_code, keychain, parallel_execution, max_concurrent_nodes } => api_mode(token, port, data_dir, allow_origins, allow_env_vars, bind, file_sandbox_dir, trusted_proxy_count, disable_shell, disable_code, keychain, parallel_execution, max_concurrent_nodes).await,
        Command::List    { server, token }       => ctl_list(&server, &token).await,
        Command::Stop    { workflow, server, token } => ctl_stop(&workflow, &server, &token).await,
        Command::Start   { workflow, server, token } => ctl_start(&workflow, &server, &token).await,
        Command::Restart { workflow, server, token } => ctl_restart(&workflow, &server, &token).await,
        Command::Status  { server, token }       => ctl_status(&server, &token).await,
        Command::Tokens  { action }              => ctl_tokens(action).await,
    }
}

async fn serve_mode(config_path: PathBuf, port_override: Option<u16>, bind: String, trusted_proxy_count: usize) {
    init_tracing();
    let config = match ServerConfig::from_file(&config_path) {
        Ok(c)  => c,
        Err(e) => { tracing::error!("Failed to load config: {}", e); std::process::exit(1); }
    };

    let status_port = port_override.unwrap_or(config.status_port);

    // Validate credentials
    let cred_resolver = Arc::new(EnvCredentialResolver::new(
        config.credential_env_vars.clone()
    ));
    if let Err(missing) = cred_resolver.validate_all() {
        let vars = missing.iter().map(|v| format!("export {}=<value>", v)).collect::<Vec<_>>().join(", ");
        tracing::error!("Missing required environment variables: {}. See .env.example in your deployment package.", vars);
        std::process::exit(1);
    }

    let workflow = match Workflow::from_json(&config.workflow_json) {
        Ok(w)  => w,
        Err(e) => { tracing::error!("Invalid workflow JSON: {}", e); std::process::exit(1); }
    };

    let trigger = match extract_trigger(&workflow) {
        Ok(t)  => t,
        Err(e) => { tracing::error!("{}", e); std::process::exit(1); }
    };

    let trigger_desc = trigger.describe();
    let data_dir = config_path.parent()
        .unwrap_or_else(|| std::path::Path::new("."))
        .to_path_buf();

    let mut registry = NodeRegistry::new();
    register_builtins(&mut registry, &data_dir, None);
    let registry = Arc::new(registry);

    let log   = LogBuffer::new(1000);
    let state = Arc::new(RwLock::new(RunState::default()));
    let run_trigger = Arc::new(tokio::sync::Notify::new());

    // Open (or create) the persistent run history database alongside the config file.
    let db_path = data_dir.join("flowo-serve.db");
    let workflow_db = match WorkflowDb::open(&db_path) {
        Ok(db) => Arc::new(db),
        Err(e) => {
            tracing::error!("Failed to open run history database at {}: {}", db_path.display(), e);
            std::process::exit(1);
        }
    };
    // Persist the workflow so the scheduler can load it via load_workflow_json().
    if let Err(e) = workflow_db.save(&workflow) {
        tracing::error!("Failed to save workflow to database: {}", e);
        std::process::exit(1);
    }

    let event_sink = Arc::new(
        EventBridge::new(log.clone(), Arc::clone(&state))
            .with_run_history(Arc::clone(&workflow_db), config.workflow_name.clone())
    );

    let db = Arc::clone(&workflow_db) as Arc<dyn SchedulerDb>;

    let daemon = Arc::new(SchedulerDaemon::new(
        Arc::clone(&db) as Arc<dyn SchedulerDb>,
        Arc::clone(&registry),
        Arc::clone(&cred_resolver) as Arc<dyn flowo_engine::executor::CredentialResolver>,
        Arc::clone(&event_sink) as Arc<dyn flowo_engine::EventSink>,
    ));

    log.push("INFO", None, format!("Starting '{}'", config.workflow_name));
    log.push("INFO", None, format!("Trigger: {}", trigger_desc));

    daemon.start_job(&workflow.id, None, Some(true))
        .unwrap_or_else(|e| log.push("ERROR", None, format!("Scheduler start failed: {:?}", e)));

    // Manual run trigger
    let daemon_rt  = Arc::clone(&daemon);
    let wf_id_rt   = workflow.id.clone();
    let run_trig   = Arc::clone(&run_trigger);
    tokio::spawn(async move {
        loop {
            run_trig.notified().await;
            let _ = daemon_rt.stop_job(&wf_id_rt);
            let _ = daemon_rt.start_job(&wf_id_rt, None, Some(true));
        }
    });

    // SIGINT + SIGTERM
    let daemon_sd  = Arc::clone(&daemon);
    let wf_id_sd   = workflow.id.clone();
    tokio::spawn(async move {
        #[cfg(unix)]
        {
            use tokio::signal::unix::{signal, SignalKind};
            let mut sigterm = signal(SignalKind::terminate()).expect("SIGTERM handler");
            tokio::select! {
                _ = tokio::signal::ctrl_c() => {},
                _ = sigterm.recv() => {},
            }
        }
        #[cfg(not(unix))]
        tokio::signal::ctrl_c().await.ok();

        tracing::info!("Shutting down");
        let _ = daemon_sd.stop_job(&wf_id_sd);
        std::process::exit(0);
    });

    tracing::info!(
        workflow = %config.workflow_name,
        trigger  = %trigger_desc,
        status_url = %format!("http://{}:{}", bind, status_port),
        "Flowo Server started in serve mode"
    );

    let status_state = status_server::StatusState {
        workflow_name: config.workflow_name,
        workflow_id:   workflow.id.clone(),
        trigger_desc,
        status_port,
        run_state:     Arc::clone(&state),
        log_buffer:    log,
        run_trigger,
        run_secret:    config.run_secret,
        rate_limiter:  Arc::new(dashmap::DashMap::new()),
        run_history:   Some(workflow_db),
        trusted_proxy_count,
    };

    let app      = status_server::router(status_state);
    let addr     = format!("{}:{}", bind, status_port);
    let listener = tokio::net::TcpListener::bind(&addr).await
        .unwrap_or_else(|e| { tracing::error!("Cannot bind {}: {}", addr, e); std::process::exit(1); });

    axum::serve(listener, app.into_make_service_with_connect_info::<std::net::SocketAddr>()).await.expect("Status server error");
}

async fn api_mode(token: Option<String>, port: u16, data_dir: String, allow_origins: Vec<String>, allow_env_vars: Vec<String>, bind: String, file_sandbox_dir: Option<std::path::PathBuf>, trusted_proxy_count: usize, disable_shell: bool, disable_code: bool, use_keychain: bool, parallel_execution: bool, max_concurrent_nodes: usize) {
    api_server::run(token, port, data_dir, allow_origins, allow_env_vars, bind, file_sandbox_dir, trusted_proxy_count, disable_shell, disable_code, use_keychain, parallel_execution, max_concurrent_nodes).await;
}

async fn ctl_list(server: &str, token: &str) {
    let jobs = api_get_items(server, token, "/api/scheduler").await;
    match jobs {
        Ok(list) if list.is_empty() => println!("No scheduled workflows."),
        Ok(list) => {
            println!("{:<36}  {:<24}  {:<10}  {:<8}  Next Run",
                "ID", "Name", "Status", "Runs");
            println!("{}", "-".repeat(100));
            for j in list {
                println!("{:<36}  {:<24}  {:<10}  {:<8}  {}",
                    j["workflow_id"].as_str().unwrap_or("?"),
                    truncate(j["workflow_name"].as_str().unwrap_or("?"), 24),
                    j["status"].as_str().unwrap_or("?"),
                    j["run_count"].as_u64().unwrap_or(0),
                    j["next_run_at"].as_str().unwrap_or("—"),
                );
            }
        }
        Err(e) => { eprintln!("ERROR: {}", e); std::process::exit(1); }
    }
}

async fn ctl_stop(workflow: &str, server: &str, token: &str) {
    let id = resolve_workflow_id(workflow, server, token).await;
    match api_post(server, token, &format!("/api/scheduler/{}/stop", id), "{}").await {
        Ok(_) => println!("Stopped '{}'.", workflow),
        Err(e) => { eprintln!("ERROR: {}", e); std::process::exit(1); }
    }
}

async fn ctl_start(workflow: &str, server: &str, token: &str) {
    let id = resolve_workflow_id(workflow, server, token).await;
    match api_post(server, token, &format!("/api/scheduler/{}/start", id),
        r#"{"always_on":false}"#).await {
        Ok(_) => println!("Started '{}'.", workflow),
        Err(e) => { eprintln!("ERROR: {}", e); std::process::exit(1); }
    }
}

async fn ctl_restart(workflow: &str, server: &str, token: &str) {
    let id = resolve_workflow_id(workflow, server, token).await;
    let _ = api_post(server, token, &format!("/api/scheduler/{}/stop", id), "{}").await;
    match api_post(server, token, &format!("/api/scheduler/{}/start", id),
        r#"{"always_on":false}"#).await {
        Ok(_) => println!("Restarted '{}'.", workflow),
        Err(e) => { eprintln!("ERROR: {}", e); std::process::exit(1); }
    }
}

async fn ctl_status(server: &str, token: &str) {
    ctl_list(server, token).await;
}

async fn ctl_tokens(action: TokenAction) {
    match action {
        TokenAction::List { server, token } => {
            let res = api_get_raw(&server, &token, "/api/tokens").await;
            match res {
                Ok(body) => {
                    let tokens: Vec<serde_json::Value> =
                        serde_json::from_str(&body).unwrap_or_else(|_| vec![]);
                    if tokens.is_empty() {
                        println!("No tokens.");
                        return;
                    }
                    println!("{:<36}  {:<20}  {:<24}  {:<8}  Revoked",
                        "ID", "Label", "Scopes", "Created");
                    println!("{}", "-".repeat(120));
                    for t in tokens {
                        let scopes = t["scopes"]
                            .as_array()
                            .map(|a| a.iter().filter_map(|v| v.as_str()).collect::<Vec<_>>().join(","))
                            .unwrap_or_default();
                        println!("{:<36}  {:<20}  {:<24}  {:<8}  {}",
                            t["token_id"].as_str().unwrap_or("?"),
                            truncate(t["label"].as_str().unwrap_or("?"), 20),
                            truncate(&scopes, 24),
                            truncate(t["created_at"].as_str().unwrap_or("?"), 8),
                            t["revoked_at"].as_str().unwrap_or("—"),
                        );
                    }
                }
                Err(e) => { eprintln!("ERROR: {}", e); std::process::exit(1); }
            }
        }
        TokenAction::Create { label, scopes, server, token } => {
            let body = serde_json::json!({"label": label, "scopes": scopes}).to_string();
            match api_post_json::<serde_json::Value>(&server, &token, "/api/tokens", &body).await {
                Ok(v) => {
                    println!("Token created. Save the raw token — it will not be shown again.");
                    println!();
                    println!("  Token:  {}", v["token"].as_str().unwrap_or("?"));
                    println!("  Label:  {}", v["label"].as_str().unwrap_or("?"));
                    println!("  Scopes: {}", v["scopes"]
                        .as_array()
                        .map(|a| a.iter().filter_map(|v| v.as_str()).collect::<Vec<_>>().join(", "))
                        .unwrap_or_default());
                }
                Err(e) => { eprintln!("ERROR: {}", e); std::process::exit(1); }
            }
        }
        TokenAction::Revoke { token_id, server, token } => {
            match api_delete(&server, &token, &format!("/api/tokens/{}", token_id)).await {
                Ok(_) => println!("Token '{}' revoked.", token_id),
                Err(e) => { eprintln!("ERROR: {}", e); std::process::exit(1); }
            }
        }
    }
}

/// Resolves a workflow name or partial ID to a full workflow ID.
async fn resolve_workflow_id(name_or_id: &str, server: &str, token: &str) -> String {
    let jobs = api_get_items(server, token, "/api/scheduler").await
        .unwrap_or_else(|e| { eprintln!("ERROR: {}", e); std::process::exit(1); });

    // Exact ID match first
    if let Some(j) = jobs.iter().find(|j| j["workflow_id"].as_str() == Some(name_or_id)) {
        return j["workflow_id"].as_str().expect("workflow_id is a string — confirmed by find predicate").to_string();
    }

    // Partial name match (case-insensitive)
    let lower = name_or_id.to_lowercase();
    let matches: Vec<_> = jobs.iter().filter(|j|
        j["workflow_name"].as_str()
            .map(|n| n.to_lowercase().contains(&lower))
            .unwrap_or(false)
    ).collect();

    match matches.len() {
        0 => {
            eprintln!("ERROR: No workflow found matching '{}'. Run `flowo-server list` to see all.", name_or_id);
            std::process::exit(1);
        }
        1 => {
            matches[0]["workflow_id"].as_str()
                .expect("workflow_id is a string — matched workflow has string id")
                .to_string()
        }
        _ => {
            eprintln!("ERROR: '{}' matches multiple workflows — use the full ID:", name_or_id);
            for j in &matches {
                eprintln!("  {}  —  {}",
                    j["workflow_id"].as_str().unwrap_or("?"),
                    j["workflow_name"].as_str().unwrap_or("?"),
                );
            }
            std::process::exit(1);
        }
    }
}

async fn api_get<T: serde::de::DeserializeOwned>(
    server: &str, token: &str, path: &str
) -> Result<T, String> {
    let client = reqwest::Client::new();
    let res = client.get(format!("{}{}", server, path))
        .header("Authorization", format!("Bearer {}", token))
        .send().await.map_err(|e| e.to_string())?;
    if !res.status().is_success() {
        return Err(format!("HTTP {}: {}", res.status(), res.text().await.unwrap_or_default()));
    }
    res.json::<T>().await.map_err(|e| e.to_string())
}

/// Fetch a paginated endpoint and return the `items` array.
/// Handles responses shaped as `{"items":[...],"total":N,...}`.
async fn api_get_items(
    server: &str, token: &str, path: &str
) -> Result<Vec<serde_json::Value>, String> {
    let raw: serde_json::Value = api_get(server, token, &format!("{}?limit=500", path)).await?;
    match raw.get("items").and_then(|v| v.as_array()) {
        Some(items) => Ok(items.clone()),
        None => Err(format!("unexpected response shape from {}: missing 'items' field", path)),
    }
}

async fn api_post(
    server: &str, token: &str, path: &str, body: &str
) -> Result<String, String> {
    let client = reqwest::Client::new();
    let res = client.post(format!("{}{}", server, path))
        .header("Authorization", format!("Bearer {}", token))
        .header("Content-Type", "application/json")
        .body(body.to_string())
        .send().await.map_err(|e| e.to_string())?;
    if !res.status().is_success() {
        return Err(format!("HTTP {}: {}", res.status(), res.text().await.unwrap_or_default()));
    }
    res.text().await.map_err(|e| e.to_string())
}

async fn api_get_raw(server: &str, token: &str, path: &str) -> Result<String, String> {
    let client = reqwest::Client::new();
    let res = client.get(format!("{}{}", server, path))
        .header("Authorization", format!("Bearer {}", token))
        .send().await.map_err(|e| e.to_string())?;
    if !res.status().is_success() {
        return Err(format!("HTTP {}: {}", res.status(), res.text().await.unwrap_or_default()));
    }
    res.text().await.map_err(|e| e.to_string())
}

async fn api_post_json<T: serde::de::DeserializeOwned>(
    server: &str, token: &str, path: &str, body: &str
) -> Result<T, String> {
    let text = api_post(server, token, path, body).await?;
    serde_json::from_str(&text).map_err(|e| e.to_string())
}

async fn api_delete(server: &str, token: &str, path: &str) -> Result<String, String> {
    let client = reqwest::Client::new();
    let res = client.delete(format!("{}{}", server, path))
        .header("Authorization", format!("Bearer {}", token))
        .send().await.map_err(|e| e.to_string())?;
    if !res.status().is_success() {
        return Err(format!("HTTP {}: {}", res.status(), res.text().await.unwrap_or_default()));
    }
    res.text().await.map_err(|e| e.to_string())
}

fn truncate(s: &str, max: usize) -> &str {
    if s.len() <= max { return s; }
    let mut boundary = max;
    while boundary > 0 && !s.is_char_boundary(boundary) {
        boundary -= 1;
    }
    &s[..boundary]
}

fn init_tracing() {
    use tracing_subscriber::{fmt, EnvFilter, layer::SubscriberExt, util::SubscriberInitExt};

    let filter = EnvFilter::try_from_env("RUST_LOG")
        .unwrap_or_else(|_| EnvFilter::new("info"));

    let json_mode = std::env::var("FLOWO_LOG_FORMAT").as_deref() == Ok("json");

    if json_mode {
        tracing_subscriber::registry()
            .with(filter)
            .with(fmt::layer().json())
            .init();
    } else {
        tracing_subscriber::registry()
            .with(filter)
            .with(fmt::layer())
            .init();
    }
}
