//! WASM plugin loader — loads third-party `.wasm` components as node implementations.
//!
//! # Architecture
//!
//! [`PluginLoader`] holds a shared [`wasmtime::Engine`] (expensive to construct; built
//! once at startup). [`load_plugins_from_dir`](PluginLoader::load_plugins_from_dir)
//! iterates a directory, calls [`load_plugin`](PluginLoader::load_plugin) for each
//! `.wasm` file, logs warnings for failures, and returns all successfully loaded nodes.
//!
//! Each [`WasmPluginNode`] is registered in [`crate::node::NodeRegistry`] identically
//! to built-in nodes and appears in the UI palette automatically.
//!
//! # Isolation model
//!
//! A fresh [`wasmtime::Store`] is created for every `execute()` call. Stores are not
//! reused across calls: one failed execution cannot corrupt the next, and there is no
//! shared mutable state between concurrent executions of the same plugin.
//!
//! The shared [`wasmtime::Engine`] and the pre-compiled
//! [`AeriniNodePre`](wit::AeriniNodePre) (which wraps [`wasmtime::component::InstancePre`])
//! are both `Clone + Send + Sync` and are cheaply shared across threads.
//!
//! # Memory limit
//!
//! Each Store is limited to [`PLUGIN_MEMORY_LIMIT`] bytes (64 MiB by default).
//! The limit is enforced by [`wasmtime::StoreLimitsBuilder`] via
//! [`wasmtime::Store::limiter`].
//!
//! # WASI surface
//!
//! Two linker calls together cover the full surface a `wasm32-wasip2` plugin needs:
//!
//! - `wasmtime_wasi::p2::add_to_linker_sync` — full WASIp2 (`wasi:cli/command` world):
//!   filesystem (sandboxed, no preopened dirs), random, clocks, stdio, exit.
//! - `wasmtime_wasi_http::p2::add_only_http_to_linker_sync` — adds `wasi:http/outgoing-handler`
//!   without duplicating the WASI interfaces already added above.
//!
//! Using just `wasmtime_wasi_http::p2::add_to_linker_sync` (the proxy world bundle) would
//! omit `wasi:filesystem`, `wasi:random`, etc., causing `linker.instantiate_pre` to fail
//! for any plugin compiled with the standard `wasm32-wasip2` target.
//!
//! Plugins cannot access the real filesystem: `WasiCtx::builder().build()` creates an
//! empty context with no preopened directories. Filesystem syscalls return errors.

use std::path::Path;
use std::sync::Arc;

use async_trait::async_trait;
use serde_json::Value;
use wasmtime::component::ResourceTable;
use wasmtime::{Config, Engine, StoreLimitsBuilder};
use wasmtime_wasi::{WasiCtx, WasiCtxView, WasiView};
use wasmtime_wasi_http::{WasiHttpCtx, p2::{WasiHttpView, WasiHttpCtxView}};

use crate::error::NodeError;
use crate::model::{NodeInput, NodeOutput, NodeType};
use crate::node::{Node, NodeRegistry};

// ── WIT bindings ──────────────────────────────────────────────────────────────

/// Bindings generated by `bindgen!` from `wit/node.wit`.
///
/// Wrapped in a private module because `bindgen!` generates types named `NodeInput`
/// and `NodeOutput` that would collide with the identically named types in
/// [`crate::model`] if expanded at the top level.
///
/// The `pub use` re-exports normalize the type path to `wit::Param`, `wit::NodeInput`,
/// etc. `bindgen!` places these types under the full package path
/// (`aerini::plugin::types`), not at the top level.
mod wit {
    wasmtime::component::bindgen!({
        world: "aerini-node",
        path: "wit",
    });

    pub use aerini::plugin::types::{NodeInput, NodeOutput, Param};
}

// ── Error type ────────────────────────────────────────────────────────────────

/// Errors that can occur while loading a WASM plugin.
#[derive(Debug, thiserror::Error)]
pub enum PluginLoadError {
    #[error("I/O error reading plugin: {0}")]
    Io(#[from] std::io::Error),

    #[error("WASM component compilation failed: {0}")]
    WasmCompile(String),

    #[error("WASM linker setup or pre-instantiation failed: {0}")]
    WasmLink(String),

    #[error("plugin does not export the `aerini-node` world")]
    MissingInterface,

    /// Kept for API compatibility; never returned by W2+ code.
    #[error("not yet implemented")]
    #[allow(dead_code)]
    NotImplemented,
}

// ── WASM Store state ──────────────────────────────────────────────────────────

/// Per-execution store state.
///
/// A fresh `PluginState` (and a fresh `Store<PluginState>`) is created for every
/// `execute()` call. This ensures complete isolation between executions.
///
/// Holds:
/// - [`WasiCtx`] — WASIp2 context (sandboxed filesystem, clocks, random, stdio).
/// - [`WasiHttpCtx`] — WASI HTTP context for outbound requests.
/// - [`ResourceTable`] — tracks host-owned resources (shared by WASI and HTTP).
/// - [`wasmtime::StoreLimits`] — enforces the 64 MiB memory cap per execution.
struct PluginState {
    wasi_ctx: WasiCtx,
    http_ctx: WasiHttpCtx,
    table: ResourceTable,
    limits: wasmtime::StoreLimits,
}

impl WasiView for PluginState {
    fn ctx(&mut self) -> WasiCtxView<'_> {
        WasiCtxView { ctx: &mut self.wasi_ctx, table: &mut self.table }
    }
}

impl WasiHttpView for PluginState {
    fn http(&mut self) -> WasiHttpCtxView<'_> {
        WasiHttpCtxView {
            ctx: &mut self.http_ctx,
            table: &mut self.table,
            hooks: Default::default(),
        }
    }
}

// ── Memory limit ──────────────────────────────────────────────────────────────

/// Maximum linear memory per plugin execution: 64 MiB.
///
/// Plugin instances that attempt to grow beyond this limit receive a WASM
/// `memory.grow` failure surfacing as a trap in the guest.
const PLUGIN_MEMORY_LIMIT: usize = 64 * 1024 * 1024;

/// CPU time limit for plugin execution, expressed in epoch ticks.
///
/// The epoch ticker thread (started in [`PluginLoader::new`]) increments the
/// engine epoch every 10 ms. A deadline of 3 000 ticks therefore limits each
/// plugin call to approximately 30 seconds of wall-clock time before it is
/// interrupted with a trap. Applies to both `describe()` at load time and
/// `execute()` per workflow run.
const PLUGIN_EPOCH_DEADLINE: u64 = 3_000;

/// Max chars of a malformed plugin `data` string echoed into the error log
/// (`wit_output_to_engine`) — avoids dumping an arbitrarily large/binary
/// blob into logs while still giving an operator enough to diagnose.
const INVALID_OUTPUT_LOG_PREVIEW_CHARS: usize = 200;

fn make_plugin_state() -> PluginState {
    PluginState {
        // No preopened directories, no inherited stdio — sandboxed context.
        // Filesystem syscalls succeed at the API level but return "not found" /
        // "permission denied" since no paths are mounted.
        wasi_ctx: WasiCtx::builder().build(),
        http_ctx: WasiHttpCtx::new(),
        table: ResourceTable::new(),
        limits: StoreLimitsBuilder::new().memory_size(PLUGIN_MEMORY_LIMIT).build(),
    }
}

fn make_store(engine: &Engine, state: PluginState) -> wasmtime::Store<PluginState> {
    let mut store = wasmtime::Store::new(engine, state);
    store.limiter(|s| &mut s.limits);
    // Trap when the epoch deadline is reached. This is the wasmtime default,
    // but set explicitly so the intent is clear. Requires epoch_interruption
    // to be enabled on the Engine (configured in PluginLoader::new).
    store.epoch_deadline_trap();
    // Set the deadline N ticks in the future. The background ticker thread
    // increments the engine epoch every 10 ms, so this is ~30 s wall-clock.
    store.set_epoch_deadline(PLUGIN_EPOCH_DEADLINE);
    store
}

// ── PluginLoader ──────────────────────────────────────────────────────────────

/// Loads WASM plugin components and registers them as [`Node`] implementations.
///
/// `Engine` is expensive to construct and designed to be shared across threads.
/// Build one `PluginLoader` at startup and reuse it for all plugin loading calls.
pub struct PluginLoader {
    engine: Engine,
}

impl PluginLoader {
    /// Construct a new `PluginLoader` with a Wasmtime engine configured for the
    /// Component Model.
    ///
    /// Returns an error if the engine cannot be initialised (e.g. unsupported CPU
    /// features on the host).
    pub fn new() -> wasmtime::Result<Self> {
        let mut config = Config::new();
        config.wasm_component_model(true);
        // Enable epoch-based CPU time limiting. All stores created from this
        // engine must call set_epoch_deadline() before executing WASM — handled
        // in make_store(). Without a deadline set, stores trap immediately.
        config.epoch_interruption(true);
        let engine = Engine::new(&config)?;

        // Spawn a process-lifetime background thread that advances the epoch
        // counter every 10 ms. The thread holds a clone of the engine (cheap —
        // Engine is Arc-backed) and runs until the process exits. Combined with
        // PLUGIN_EPOCH_DEADLINE = 3 000, this gives plugins ~30 s per call.
        let ticker_engine = engine.clone();
        std::thread::Builder::new()
            .name("wasm-epoch-ticker".to_string())
            .spawn(move || loop {
                std::thread::sleep(std::time::Duration::from_millis(10));
                ticker_engine.increment_epoch();
            })
            .expect("failed to spawn wasm epoch ticker thread");

        Ok(Self { engine })
    }

    /// Load a single WASM plugin from `path`.
    ///
    /// Steps:
    /// 1. Read the file (→ [`PluginLoadError::Io`] on failure).
    /// 2. Compile to a component (→ [`PluginLoadError::WasmCompile`] on failure).
    /// 3. Build a linker with full WASIp2 + HTTP and pre-instantiate
    ///    (→ [`PluginLoadError::WasmLink`] on failure).
    /// 4. Validate that the component exports the `aerini-node` world
    ///    (→ [`PluginLoadError::MissingInterface`] if absent).
    /// 5. Call `describe()` once to populate the [`NodeDescriptor`](crate::node::NodeDescriptor).
    ///
    /// The `describe()` result is cached in [`WasmPluginNode`] for the lifetime
    /// of the process — it is never called again after load time.
    pub fn load_plugin(&self, path: &Path) -> Result<Arc<dyn Node>, PluginLoadError> {
        // Step 1: read — produces Io error (not WasmCompile) for missing files.
        let bytes = std::fs::read(path)?;

        // Step 2: compile. Accepts WAT text or WASM binary — wasmtime detects by magic.
        let component = wasmtime::component::Component::new(&self.engine, &bytes)
            .map_err(|e| PluginLoadError::WasmCompile(e.to_string()))?;

        // Step 3: linker + pre-instantiation.
        //
        // Two separate calls are required:
        // (a) `wasmtime_wasi::p2::add_to_linker_sync` — satisfies all `wasi:cli/command`
        //     imports (filesystem, random, clocks, stdio) that `wasm32-wasip2` binaries
        //     unconditionally import via Rust's standard library.
        // (b) `wasmtime_wasi_http::p2::add_only_http_to_linker_sync` — adds only the
        //     `wasi:http/outgoing-handler` interface without duplicating the WASI
        //     interfaces already registered in (a).
        //
        // Using just `wasmtime_wasi_http::p2::add_to_linker_sync` (the proxy world bundle)
        // instead of (a)+(b) would omit `wasi:filesystem`, `wasi:random`, etc., causing
        // `linker.instantiate_pre` to fail for every standard `wasm32-wasip2` plugin.
        let mut linker = wasmtime::component::Linker::<PluginState>::new(&self.engine);
        wasmtime_wasi::p2::add_to_linker_sync(&mut linker)
            .map_err(|e| PluginLoadError::WasmLink(e.to_string()))?;
        wasmtime_wasi_http::p2::add_only_http_to_linker_sync(&mut linker)
            .map_err(|e| PluginLoadError::WasmLink(e.to_string()))?;

        let instance_pre = linker.instantiate_pre(&component)
            .map_err(|e| PluginLoadError::WasmLink(e.to_string()))?;

        // Step 4: validate the `aerini-node` world export exists.
        let pre = wit::AeriniNodePre::new(instance_pre)
            .map_err(|_| PluginLoadError::MissingInterface)?;

        // Step 5: call describe() once to get node metadata.
        let mut store = make_store(&self.engine, make_plugin_state());

        let bindings = pre.instantiate(&mut store)
            .map_err(|e| PluginLoadError::WasmLink(e.to_string()))?;

        let descriptor = bindings
            .aerini_plugin_node()
            .call_describe(&mut store)
            .map_err(|e| PluginLoadError::WasmLink(e.to_string()))?;

        // Leak type_id and display_name once per plugin load — bounded intentional leak:
        // plugins are loaded once at process start and live for the process lifetime.
        let type_id: &'static str = Box::leak(descriptor.type_id.into_boxed_str());
        let display_name: &'static str = Box::leak(descriptor.display_name.into_boxed_str());

        let node_type = match descriptor.category.as_str() {
            "ai" => NodeType::Ai,
            "logic" => NodeType::Logic,
            "utility" => NodeType::Utility,
            "action" => NodeType::Action,
            other => {
                tracing::warn!(
                    "plugin '{}': unrecognised category '{}' — defaulting to Action",
                    type_id,
                    other
                );
                NodeType::Action
            }
        };

        // JSON Schema strings from the plugin — fall back to empty schema on parse failure.
        let input_schema: Value = serde_json::from_str(&descriptor.input_schema)
            .unwrap_or_else(|_| Value::Object(serde_json::Map::new()));
        let output_schema: Value = serde_json::from_str(&descriptor.output_schema)
            .unwrap_or_else(|_| Value::Object(serde_json::Map::new()));

        Ok(Arc::new(WasmPluginNode {
            engine: self.engine.clone(),
            pre,
            type_id,
            display_name,
            node_type,
            input_schema,
            output_schema,
        }))
    }

    /// Load all `.wasm` files from `dir` as plugins.
    ///
    /// Files that fail to load are logged as warnings and skipped — they do not
    /// prevent other plugins from loading or crash the process.
    ///
    /// Returns an empty `Vec` if the directory cannot be read.
    pub fn load_plugins_from_dir(&self, dir: &Path) -> Vec<Arc<dyn Node>> {
        let entries = match std::fs::read_dir(dir) {
            Ok(e) => e,
            Err(err) => {
                tracing::warn!(
                    "plugin_loader: cannot read plugin directory {}: {}",
                    dir.display(),
                    err
                );
                return vec![];
            }
        };

        let mut nodes: Vec<Arc<dyn Node>> = Vec::new();

        for entry in entries {
            let entry = match entry {
                Ok(e) => e,
                Err(err) => {
                    tracing::warn!("plugin_loader: error reading directory entry: {}", err);
                    continue;
                }
            };

            let path = entry.path();

            if path.extension().and_then(|e| e.to_str()) != Some("wasm") {
                continue;
            }

            match self.load_plugin(&path) {
                Ok(node) => {
                    tracing::info!(
                        "plugin_loader: loaded plugin '{}' from {}",
                        node.type_id(),
                        path.display()
                    );
                    nodes.push(node);
                }
                Err(err) => {
                    tracing::warn!(
                        "plugin_loader: skipping {}: {}",
                        path.display(),
                        err
                    );
                }
            }
        }

        nodes
    }
}

// ── WasmPluginNode ────────────────────────────────────────────────────────────

/// A node implementation backed by a WASM component.
///
/// Registered in [`NodeRegistry`] identically to built-in nodes and appears in the
/// UI palette via the cached [`NodeDescriptor`](crate::node::NodeDescriptor) with
/// no frontend changes required.
///
/// # Execution isolation
///
/// Each `execute()` call creates a fresh [`wasmtime::Store<PluginState>`] from the
/// shared engine and the pre-compiled [`wit::AeriniNodePre`]. The `Store` is created
/// and consumed entirely within a `spawn_blocking` closure — it never crosses an
/// `await` point and is dropped at the end of the call.
///
/// # Input serialization
///
/// The executor provides `input.input` as a merged JSON object (config + resolved
/// credentials). This is serialized to `Vec<wit::Param>` key-value pairs and passed
/// to the plugin as `NodeInput.params`. `credentials` is left empty because the
/// executor has already resolved and merged credential values into `input.input`.
///
/// # Output deserialization
///
/// `NodeOutput.data` is a JSON string. On success it is parsed to `serde_json::Value`;
/// a parse failure is treated as a genuine, logged node failure (`wasm_invalid_output`),
/// not silently substituted with empty output.
///
/// # Static string fields
///
/// `type_id` and `display_name` are [`Box::leak`]ed once at load time. This is a
/// bounded, intentional leak: plugins are loaded once at process start and never
/// unloaded.
pub struct WasmPluginNode {
    /// Shared engine — cheap to clone (internally ref-counted).
    engine: Engine,
    /// Pre-compiled component with import-satisfaction already verified.
    /// `Clone + Send + Sync`. Re-instantiated per `execute()` call.
    pre: wit::AeriniNodePre<PluginState>,
    type_id: &'static str,
    display_name: &'static str,
    node_type: NodeType,
    input_schema: Value,
    output_schema: Value,
}

#[async_trait]
impl Node for WasmPluginNode {
    fn type_id(&self) -> &'static str {
        self.type_id
    }

    fn display_name(&self) -> &'static str {
        self.display_name
    }

    fn node_type(&self) -> NodeType {
        self.node_type.clone()
    }

    fn version(&self) -> &'static str {
        // WASM plugins do not expose a version via WIT. Plugins may embed their
        // version in type_id (e.g. "com.example.my-node@1.2.0") if needed.
        "1.0.0"
    }

    fn is_plugin(&self) -> bool {
        true
    }

    fn input_schema(&self) -> Value {
        self.input_schema.clone()
    }

    fn output_schema(&self) -> Value {
        self.output_schema.clone()
    }

    /// Execute the plugin node.
    ///
    /// Runs synchronous Wasmtime instantiation + function call in
    /// `tokio::task::spawn_blocking` so the async executor is never blocked.
    /// A fresh `Store` is created per call for full execution isolation.
    async fn execute(&self, input: NodeInput) -> NodeOutput {
        let engine = self.engine.clone();
        let pre = self.pre.clone();
        let wit_input = engine_input_to_wit(&input);

        let result = tokio::task::spawn_blocking(move || {
            let mut store = make_store(&engine, make_plugin_state());

            let bindings = pre.instantiate(&mut store).map_err(|e| e.to_string())?;

            bindings
                .aerini_plugin_node()
                .call_execute(&mut store, &wit_input)
                .map_err(|e| e.to_string())
        })
        .await;

        match result {
            Ok(Ok(out)) => wit_output_to_engine(out),
            // Traps are unrecoverable: retrying the same input produces the same trap.
            Ok(Err(trap_msg)) => NodeOutput::failure(NodeError::unrecoverable(
                "wasm_trap",
                format!("plugin execution trapped: {trap_msg}"),
            )),
            Err(join_err) => NodeOutput::failure(NodeError::unrecoverable(
                "wasm_panic",
                format!("plugin task panicked: {join_err}"),
            )),
        }
    }
}

// ── Input / output conversion ─────────────────────────────────────────────────

/// Flatten the merged JSON input into a `Vec<Param>` for the WIT interface.
///
/// The executor merges config and resolved credentials into `input.input` as a
/// JSON object. Each top-level key becomes a `Param`. Non-string values are
/// serialized to their JSON text representation (e.g. numbers, booleans, objects).
fn engine_input_to_wit(input: &NodeInput) -> wit::NodeInput {
    let params = match &input.input {
        Value::Object(map) => map
            .iter()
            .map(|(k, v)| wit::Param {
                key: k.clone(),
                value: match v {
                    Value::String(s) => s.clone(),
                    other => other.to_string(),
                },
            })
            .collect(),
        _ => vec![],
    };

    wit::NodeInput {
        params,
        credentials: vec![], // already merged into input.input by the executor
    }
}

/// Convert a WIT `NodeOutput` record to the engine's [`NodeOutput`].
fn wit_output_to_engine(out: wit::NodeOutput) -> NodeOutput {
    if out.success {
        match serde_json::from_str::<Value>(&out.data) {
            Ok(value) => NodeOutput::success(value),
            Err(parse_err) => {
                // A plugin that reports success but returns non-JSON `data` was
                // previously papered over as an empty `{}` object with no error
                // and no log line — indistinguishable from a plugin that legitimately
                // returns no data. Surface it as a real, logged failure instead.
                let preview: String = out.data.chars().take(INVALID_OUTPUT_LOG_PREVIEW_CHARS).collect();
                tracing::error!(
                    "plugin_loader: plugin reported success but `data` is not valid JSON: {} (data preview: {:?})",
                    parse_err,
                    preview
                );
                NodeOutput::failure(NodeError::unrecoverable(
                    "wasm_invalid_output",
                    format!(
                        "plugin reported success but its output was not valid JSON: {parse_err}"
                    ),
                ))
            }
        }
    } else {
        NodeOutput::failure(NodeError {
            code: out.error_code,
            message: out.error_message,
            recoverable: out.recoverable,
        })
    }
}

// ── Public API ────────────────────────────────────────────────────────────────

/// Load all WASM plugins from `plugin_dir` and register them in `registry`.
///
/// Constructs a [`PluginLoader`] (and a Wasmtime engine) internally.
/// Called by `aerini-server` and `src-tauri` after [`crate::nodes::register_builtins`].
/// Seals the built-in namespace before registering any plugins so that a plugin
/// whose `type_id` collides with a built-in is rejected rather than silently replacing it.
///
/// If the Wasmtime engine fails to initialise, an error is logged and the function
/// returns without registering any plugins — the process continues normally.
pub fn load_plugins(registry: &mut NodeRegistry, plugin_dir: &Path) {
    // Seal the built-in namespace before loading any plugins so that a plugin
    // cannot shadow a built-in node type (e.g. "http_request", "shell_exec").
    registry.seal_builtins();

    // SECURITY NOTICE: WASM plugins loaded here have unrestricted outbound HTTP
    // access via the wasi:http/outgoing-handler interface. This bypasses the
    // application-layer SSRF guards in check_ssrf_ip() — a plugin can reach
    // RFC 1918 addresses, Azure IMDS (168.63.129.16), and any other internal
    // endpoint that would otherwise be blocked. Treat the plugin directory as a
    // trust boundary equivalent to running arbitrary native code. In server/API
    // mode, a supply-chain-compromised .wasm file silently gains unrestricted
    // internal network access. Enforce network-level egress filtering to block
    // outbound connections to private IP ranges from the server process.
    tracing::warn!(
        "plugin_loader: loading WASM plugins from '{}'. Plugins have unrestricted outbound HTTP access (wasi:http bypasses SSRF guards). Only load plugins from trusted sources. Enforce network-level egress filtering in server/API deployments.",
        plugin_dir.display()
    );

    let loader = match PluginLoader::new() {
        Ok(l) => l,
        Err(e) => {
            tracing::error!(
                "plugin_loader: failed to initialise Wasmtime engine: {}",
                e
            );
            return;
        }
    };

    let nodes = loader.load_plugins_from_dir(plugin_dir);
    let mut loaded = 0usize;
    let mut rejected = 0usize;
    for node in nodes {
        match registry.register_plugin(node) {
            Ok(()) => loaded += 1,
            Err(_) => rejected += 1,   // warning already emitted inside register_plugin
        }
    }

    if rejected > 0 {
        tracing::warn!(
            "plugin_loader: {} plugin node(s) rejected (built-in type_id collision) from {}",
            rejected,
            plugin_dir.display()
        );
    }
    tracing::info!(
        "plugin_loader: loaded {} plugin node(s) from {}",
        loaded,
        plugin_dir.display()
    );
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn loader() -> PluginLoader {
        PluginLoader::new().expect("Wasmtime engine init failed in test")
    }

    /// Non-existent path must return `PluginLoadError::Io`.
    #[test]
    fn load_plugin_nonexistent_file_returns_io_error() {
        let l = loader();
        let result = l.load_plugin(Path::new("/nonexistent/path/to/plugin.wasm"));
        assert!(result.is_err(), "expected Io error, got Ok");
        let err = result.err().unwrap();
        assert!(
            matches!(err, PluginLoadError::Io(_)),
            "expected Io, got: {err:?}"
        );
    }

    /// A valid WASM component that does NOT export the `aerini-node` world must
    /// return `PluginLoadError::MissingInterface`.
    ///
    /// Uses `(component)` — the smallest valid Component Model component. It has no
    /// exports and no imports, so `linker.instantiate_pre` succeeds (no unsatisfied
    /// imports) but `AeriniNodePre::new` fails (no `aerini:plugin/node` export).
    #[test]
    fn load_plugin_empty_component_returns_missing_interface() {
        let l = loader();

        let mut tmp = tempfile::NamedTempFile::new().expect("tempfile create failed");
        tmp.write_all(b"(component)").expect("tempfile write failed");
        tmp.flush().expect("tempfile flush failed");

        let result = l.load_plugin(tmp.path());
        assert!(result.is_err(), "expected MissingInterface error, got Ok");
        let err = result.err().unwrap();
        assert!(
            matches!(err, PluginLoadError::MissingInterface),
            "expected MissingInterface, got: {err:?}"
        );
    }
}
