//! WASM plugin loader — loads third-party `.wasm` components as node implementations.
//!
//! # Architecture
//!
//! [`PluginLoader`] holds a shared [`wasmtime::Engine`] (expensive to construct; built
//! once per process via [`PluginLoader::shared`], which every call site — startup
//! loading and later, repeatable inspection/listing calls alike — goes through
//! instead of [`PluginLoader::new`] directly).
//! [`load_plugins_from_dir`](PluginLoader::load_plugins_from_dir)
//! iterates a directory, calls [`load_plugin`](PluginLoader::load_plugin) for each
//! `.wasm` file, logs warnings for failures, and returns all successfully loaded nodes.
//! [`describe_plugin`](PluginLoader::describe_plugin) does the same compile/link/describe
//! work as `load_plugin` for a single file but returns owned metadata instead of a
//! registered, `'static`-leaking [`Node`] — the path for callers (e.g. a UI listing
//! command) that need to call this repeatedly rather than once per process.
//!
//! Each [`WasmPluginNode`] is registered in [`crate::node::NodeRegistry`] identically
//! to built-in nodes and appears in the UI palette automatically.
//!
//! # Isolation model
//!
//! A fresh [`wasmtime::Store`] is created for every `execute()` call. Stores are not
//! reused across calls: one failed execution cannot corrupt the next, and there is no
//! shared mutable state between concurrent executions of the same plugin.
//!
//! The shared [`wasmtime::Engine`] and the pre-compiled
//! [`AeriniNodePre`](wit::AeriniNodePre) (which wraps [`wasmtime::component::InstancePre`])
//! are both `Clone + Send + Sync` and are cheaply shared across threads.
//!
//! # Memory limit
//!
//! Each Store is limited to [`PLUGIN_MEMORY_LIMIT`] bytes (64 MiB by default).
//! The limit is enforced by [`wasmtime::StoreLimitsBuilder`] via
//! [`wasmtime::Store::limiter`].
//!
//! # WASI surface
//!
//! Two linker calls together cover the full surface a `wasm32-wasip2` plugin needs:
//!
//! - `wasmtime_wasi::p2::add_to_linker_sync` — full WASIp2 (`wasi:cli/command` world):
//!   filesystem (sandboxed, no preopened dirs), random, clocks, stdio, exit.
//! - `wasmtime_wasi_http::p2::add_only_http_to_linker_sync` — adds `wasi:http/outgoing-handler`
//!   without duplicating the WASI interfaces already added above.
//!
//! Using just `wasmtime_wasi_http::p2::add_to_linker_sync` (the proxy world bundle) would
//! omit `wasi:filesystem`, `wasi:random`, etc., causing `linker.instantiate_pre` to fail
//! for any plugin compiled with the standard `wasm32-wasip2` target.
//!
//! Plugins cannot access the real filesystem: `WasiCtx::builder().build()` creates an
//! empty context with no preopened directories. Filesystem syscalls return errors.
//!
//! # Outbound HTTP
//!
//! Every request a plugin sends through `wasi:http/outgoing-handler` is checked by
//! [`PluginHttpHooks::send_request`] against this crate's standard SSRF policy — the
//! same `SsrfPolicy::Strict` the Database and HTTP nodes enforce — before
//! `wasmtime_wasi_http`'s default send path is allowed to run it. See
//! [`check_plugin_request_ssrf`] for exactly what is and isn't caught.

use std::collections::HashMap;
use std::net::ToSocketAddrs;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex, OnceLock};
use std::time::SystemTime;

use async_trait::async_trait;
use hyper::Request;
use serde_json::Value;
use wasmtime::component::ResourceTable;
use wasmtime::{Config, Engine, StoreLimitsBuilder};
use wasmtime_wasi::{WasiCtx, WasiCtxView, WasiView};
use wasmtime_wasi_http::p2::bindings::http::types::ErrorCode;
use wasmtime_wasi_http::p2::body::HyperOutgoingBody;
use wasmtime_wasi_http::p2::types::{HostFutureIncomingResponse, OutgoingRequestConfig};
use wasmtime_wasi_http::{WasiHttpCtx, p2::{HttpResult, WasiHttpCtxView, WasiHttpHooks, WasiHttpView, default_send_request}};

use crate::error::NodeError;
use crate::model::{NodeInput, NodeOutput, NodeType};
use crate::node::{Node, NodeRegistry};
use crate::nodes::util::{SsrfPolicy, check_ssrf_ip};

// ── WIT bindings ──────────────────────────────────────────────────────────────

/// Bindings generated by `bindgen!` from `wit/node.wit`.
///
/// Wrapped in a private module because `bindgen!` generates types named `NodeInput`
/// and `NodeOutput` that would collide with the identically named types in
/// [`crate::model`] if expanded at the top level.
///
/// The `pub use` re-exports normalize the type path to `wit::Param`, `wit::NodeInput`,
/// etc. `bindgen!` places these types under the full package path
/// (`aerini::plugin::types`), not at the top level.
mod wit {
    wasmtime::component::bindgen!({
        world: "aerini-node",
        path: "wit",
    });

    pub use aerini::plugin::types::{NodeInput, NodeOutput, Param};
}

// ── Error type ────────────────────────────────────────────────────────────────

/// Errors that can occur while loading a WASM plugin.
#[derive(Debug, thiserror::Error)]
pub enum PluginLoadError {
    #[error("I/O error reading plugin: {0}")]
    Io(#[from] std::io::Error),

    #[error("WASM component compilation failed: {0}")]
    WasmCompile(String),

    #[error("WASM linker setup or pre-instantiation failed: {0}")]
    WasmLink(String),

    #[error("plugin does not export the `aerini-node` world")]
    MissingInterface,

    /// Kept for API compatibility; not returned by any current code path.
    #[error("not yet implemented")]
    #[allow(dead_code)]
    NotImplemented,
}

// ── WASM Store state ──────────────────────────────────────────────────────────

/// Per-execution store state.
///
/// A fresh `PluginState` (and a fresh `Store<PluginState>`) is created for every
/// `execute()` call. This ensures complete isolation between executions.
///
/// Holds:
/// - [`WasiCtx`] — WASIp2 context (sandboxed filesystem, clocks, random, stdio).
/// - [`WasiHttpCtx`] — WASI HTTP context for outbound requests.
/// - [`ResourceTable`] — tracks host-owned resources (shared by WASI and HTTP).
/// - [`wasmtime::StoreLimits`] — enforces the 64 MiB memory cap per execution.
/// - [`PluginHttpHooks`] — enforces this crate's SSRF policy on every outbound
///   request before `wasi:http`'s default send path is allowed to run it.
struct PluginState {
    wasi_ctx: WasiCtx,
    http_ctx: WasiHttpCtx,
    table: ResourceTable,
    limits: wasmtime::StoreLimits,
    http_hooks: PluginHttpHooks,
}

impl WasiView for PluginState {
    fn ctx(&mut self) -> WasiCtxView<'_> {
        WasiCtxView { ctx: &mut self.wasi_ctx, table: &mut self.table }
    }
}

impl WasiHttpView for PluginState {
    fn http(&mut self) -> WasiHttpCtxView<'_> {
        WasiHttpCtxView {
            ctx: &mut self.http_ctx,
            table: &mut self.table,
            hooks: &mut self.http_hooks,
        }
    }
}

// ── Outbound HTTP SSRF enforcement ─────────────────────────────────────────────

/// `wasi:http/outgoing-handler`'s default send path (`default_send_request`) connects
/// straight to whatever host the guest asks for — it has no knowledge of this
/// application's SSRF policy. `WasiHttpHooks::send_request` is the documented
/// interception point, so plugin traffic is now checked exactly like any other
/// node's HTTP/DB egress before `default_send_request` is allowed to run.
struct PluginHttpHooks;

impl WasiHttpHooks for PluginHttpHooks {
    fn send_request(
        &mut self,
        request: Request<HyperOutgoingBody>,
        config: OutgoingRequestConfig,
    ) -> HttpResult<HostFutureIncomingResponse> {
        if let Err(code) = check_plugin_request_ssrf(request.uri()) {
            return Ok(HostFutureIncomingResponse::ready(Ok(Err(code))));
        }
        Ok(default_send_request(request, config))
    }
}

/// Applies this crate's standard SSRF policy (`SsrfPolicy::Strict` — the same
/// policy the Database and HTTP nodes enforce, see `nodes::util::check_ssrf_ip`)
/// to a WASM plugin's outbound request URI before it is sent.
///
/// IP-literal hosts are checked directly (IPv6 authority brackets are stripped
/// first — `hyper::Uri::host()` keeps them). Domain names are resolved with a
/// blocking DNS lookup and every returned address is checked; safe to block on
/// here since `send_request` only ever runs inside the `tokio::task::spawn_blocking`
/// closure in `WasmPluginNode::execute`, never on an async worker thread. A missing
/// or unparsable host, a failed resolution, or an empty result set all reject the
/// request — fail closed, matching this crate's existing SSRF-check convention
/// (`nodes::util::check_host_ssrf`).
///
/// Residual limits, same caveat `check_host_ssrf` itself documents:
/// - A DNS-rebinding TOCTOU gap remains between this check and the connect
///   `default_send_request` performs a moment later.
/// - No explicit timeout on the resolution call, consistent with every other
///   SSRF check in this crate — a stalled resolver holds one blocking-pool
///   thread, not an async worker.
///
/// Both require network-level egress filtering to close fully — see the
/// startup warning in `load_plugins`.
fn check_plugin_request_ssrf(uri: &hyper::Uri) -> Result<(), ErrorCode> {
    let host = uri.host().ok_or(ErrorCode::HttpRequestUriInvalid)?;
    let port = uri
        .port_u16()
        .unwrap_or(if uri.scheme_str() == Some("https") { 443 } else { 80 });

    // `hyper::Uri::host()` keeps the `[...]` brackets around an IPv6 literal;
    // strip them before attempting to parse as an IP address.
    let ip_candidate = host.strip_prefix('[').and_then(|s| s.strip_suffix(']')).unwrap_or(host);
    if let Ok(ip) = ip_candidate.parse::<std::net::IpAddr>() {
        return check_ssrf_ip(ip, SsrfPolicy::Strict).map_err(|_| ErrorCode::DestinationIpProhibited);
    }

    let lower = host.to_ascii_lowercase();
    if lower == "localhost" || lower.ends_with(".localhost") || lower == "metadata.google.internal" {
        return Err(ErrorCode::DestinationIpProhibited);
    }

    let addrs = (host, port).to_socket_addrs().map_err(|_| ErrorCode::DestinationNotFound)?;
    let mut resolved_any = false;
    for addr in addrs {
        resolved_any = true;
        check_ssrf_ip(addr.ip(), SsrfPolicy::Strict).map_err(|_| ErrorCode::DestinationIpProhibited)?;
    }
    if !resolved_any {
        return Err(ErrorCode::DestinationNotFound);
    }
    Ok(())
}

#[cfg(test)]
mod plugin_http_hooks_tests {
    use super::{check_plugin_request_ssrf, ErrorCode};

    #[test]
    fn public_ip_allowed() {
        let uri: hyper::Uri = "http://93.184.216.34/".parse().unwrap();
        assert!(check_plugin_request_ssrf(&uri).is_ok());
    }

    #[test]
    fn private_ip_blocked() {
        let v4: hyper::Uri = "http://192.168.1.1/".parse().unwrap();
        assert!(matches!(check_plugin_request_ssrf(&v4), Err(ErrorCode::DestinationIpProhibited)));

        // IPv6 loopback via bracketed authority -- `hyper::Uri::host()` keeps the
        // brackets, exercising the strip-before-parse path above.
        let v6: hyper::Uri = "http://[::1]:8080/".parse().unwrap();
        assert!(matches!(check_plugin_request_ssrf(&v6), Err(ErrorCode::DestinationIpProhibited)));
    }

    #[test]
    fn relative_uri_without_host_rejected() {
        let uri: hyper::Uri = "/no-authority".parse().unwrap();
        assert!(matches!(check_plugin_request_ssrf(&uri), Err(ErrorCode::HttpRequestUriInvalid)));
    }
}

// ── Memory limit ──────────────────────────────────────────────────────────────

/// Maximum linear memory per plugin execution: 64 MiB.
///
/// Plugin instances that attempt to grow beyond this limit receive a WASM
/// `memory.grow` failure surfacing as a trap in the guest.
const PLUGIN_MEMORY_LIMIT: usize = 64 * 1024 * 1024;

/// CPU time limit for plugin execution, expressed in epoch ticks.
///
/// The epoch ticker thread (started in [`PluginLoader::new`]) increments the
/// engine epoch every 10 ms. A deadline of 3 000 ticks therefore limits each
/// plugin call to approximately 30 seconds of wall-clock time before it is
/// interrupted with a trap. Applies to both `describe()` at load time and
/// `execute()` per workflow run.
const PLUGIN_EPOCH_DEADLINE: u64 = 3_000;

/// Max chars of a malformed plugin `data` string echoed into the error log
/// (`wit_output_to_engine`) — avoids dumping an arbitrarily large/binary
/// blob into logs while still giving an operator enough to diagnose.
const INVALID_OUTPUT_LOG_PREVIEW_CHARS: usize = 200;

fn make_plugin_state() -> PluginState {
    PluginState {
        // No preopened directories, no inherited stdio — sandboxed context.
        // Filesystem syscalls succeed at the API level but return "not found" /
        // "permission denied" since no paths are mounted.
        wasi_ctx: WasiCtx::builder().build(),
        http_ctx: WasiHttpCtx::new(),
        table: ResourceTable::new(),
        limits: StoreLimitsBuilder::new().memory_size(PLUGIN_MEMORY_LIMIT).build(),
        http_hooks: PluginHttpHooks,
    }
}

fn make_store(engine: &Engine, state: PluginState) -> wasmtime::Store<PluginState> {
    let mut store = wasmtime::Store::new(engine, state);
    store.limiter(|s| &mut s.limits);
    // Trap when the epoch deadline is reached. This is the wasmtime default,
    // but set explicitly so the intent is clear. Requires epoch_interruption
    // to be enabled on the Engine (configured in PluginLoader::new).
    store.epoch_deadline_trap();
    // Set the deadline N ticks in the future. The background ticker thread
    // increments the engine epoch every 10 ms, so this is ~30 s wall-clock.
    store.set_epoch_deadline(PLUGIN_EPOCH_DEADLINE);
    store
}

// ── PluginLoader ──────────────────────────────────────────────────────────────

/// Loads WASM plugin components and registers them as [`Node`] implementations.
///
/// `Engine` is expensive to construct and designed to be shared across threads.
/// Build one `PluginLoader` at startup and reuse it for all plugin loading calls —
/// in practice, call [`PluginLoader::shared`] rather than [`PluginLoader::new`]
/// directly, so this invariant is enforced by construction rather than by
/// caller discipline.
pub struct PluginLoader {
    engine: Engine,
    /// Compiled-`Component` cache keyed by plugin path — see
    /// `compile_and_link` for the caching/invalidation contract.
    component_cache: Mutex<HashMap<PathBuf, CachedComponent>>,
    /// Counts real (cache-miss) compiles — lets tests assert cache-hit
    /// behavior directly instead of only inferring it from timing.
    /// Per-instance (not a shared global) so tests running in parallel
    /// can't interfere with each other's counts. Always present (one
    /// `AtomicUsize`, one relaxed-cost increment per real compile — compile
    /// itself dwarfs this) rather than `#[cfg(test)]`-gated, since only the
    /// *definition* form of field-level `cfg` is a confirmed-safe pattern;
    /// only the read accessor below needs to be test-only.
    #[allow(dead_code)]
    compile_count: std::sync::atomic::AtomicUsize,
}

/// One cached, already-compiled [`wasmtime::component::Component`] plus the
/// file fingerprint (mtime, length) it was compiled from.
///
/// `Component::clone` is a cheap, `Arc`-backed shallow copy, not a
/// recompilation — it creates a new reference to the existing component
/// rather than an entirely new one, so serving a cache hit costs one
/// `stat()` plus one cheap clone, versus a full read + Cranelift compile
/// on a miss.
struct CachedComponent {
    fingerprint: (Option<SystemTime>, u64),
    component: wasmtime::component::Component,
}

/// Process-wide, lazily-constructed [`PluginLoader`].
///
/// [`PluginLoader::new`] builds a `wasmtime::Engine` and spawns a permanent,
/// process-lifetime epoch-ticker OS thread — both are meant to exist at most
/// once per process (see the struct-level doc comment above). Every call site
/// that needs a loader — [`load_plugins`] at startup, and any UI-facing
/// listing/inspection command — goes through [`PluginLoader::shared`] instead
/// of calling `new()` itself, so a caller invoked repeatedly within one
/// process (e.g. a Plugins settings panel re-listing installed plugins) can
/// never construct a second engine/thread.
static SHARED_LOADER: OnceLock<Result<PluginLoader, String>> = OnceLock::new();

/// Metadata about a plugin, obtained without registering it as a live
/// [`Node`] and without leaking any memory.
///
/// [`PluginLoader::load_plugin`] returns an `Arc<dyn Node>` whose `type_id`
/// and `display_name` are [`Box::leak`]ed, because the [`Node`] trait
/// requires `&'static str` — correct and bounded when called once per
/// plugin at process startup (see [`load_plugins`]), but not safe to call
/// repeatedly. [`PluginLoader::describe_plugin`] runs the identical
/// compile/link/describe steps but returns owned data instead, so it is
/// safe to call as many times as a caller needs (e.g. every time a UI
/// panel lists installed plugins).
pub struct PluginDescriptor {
    pub type_id: String,
    pub display_name: String,
    pub node_type: NodeType,
}

/// Maps a plugin-supplied category string to a [`NodeType`], defaulting to
/// [`NodeType::Action`] (with a warning) for any unrecognised value. Shared
/// by [`PluginLoader::load_plugin`] and [`PluginLoader::describe_plugin`] so
/// the mapping — and its warning — can't drift between the two call paths.
fn category_to_node_type(category: &str, type_id_for_log: &str) -> NodeType {
    match category {
        "ai" => NodeType::Ai,
        "logic" => NodeType::Logic,
        "utility" => NodeType::Utility,
        "action" => NodeType::Action,
        other => {
            tracing::warn!(
                "plugin '{}': unrecognised category '{}' — defaulting to Action",
                type_id_for_log,
                other
            );
            NodeType::Action
        }
    }
}

impl PluginLoader {
    /// Construct a new `PluginLoader` with a Wasmtime engine configured for the
    /// Component Model.
    ///
    /// Returns an error if the engine cannot be initialised (e.g. unsupported CPU
    /// features on the host).
    pub fn new() -> wasmtime::Result<Self> {
        let mut config = Config::new();
        config.wasm_component_model(true);
        // Enable epoch-based CPU time limiting. All stores created from this
        // engine must call set_epoch_deadline() before executing WASM — handled
        // in make_store(). Without a deadline set, stores trap immediately.
        config.epoch_interruption(true);
        let engine = Engine::new(&config)?;

        // Spawn a process-lifetime background thread that advances the epoch
        // counter every 10 ms. The thread holds a clone of the engine (cheap —
        // Engine is Arc-backed) and runs until the process exits. Combined with
        // PLUGIN_EPOCH_DEADLINE = 3 000, this gives plugins ~30 s per call.
        let ticker_engine = engine.clone();
        std::thread::Builder::new()
            .name("wasm-epoch-ticker".to_string())
            .spawn(move || loop {
                std::thread::sleep(std::time::Duration::from_millis(10));
                ticker_engine.increment_epoch();
            })
            .expect("failed to spawn wasm epoch ticker thread");

        Ok(Self {
            engine,
            component_cache: Mutex::new(HashMap::new()),
            compile_count: std::sync::atomic::AtomicUsize::new(0),
        })
    }

    /// Number of real (cache-miss) compiles performed by this instance so
    /// far. Test-only — see the `compile_count` field doc above.
    #[cfg(test)]
    fn compile_count(&self) -> usize {
        self.compile_count.load(std::sync::atomic::Ordering::SeqCst)
    }

    /// Returns the process-wide shared [`PluginLoader`], constructing it on
    /// the first call and reusing it — and its one `Engine` and one
    /// epoch-ticker thread — for every later call, from any caller, for the
    /// rest of the process's lifetime.
    ///
    /// If [`PluginLoader::new`] fails (e.g. unsupported CPU features on the
    /// host), the error is cached and returned again on every subsequent
    /// call rather than retried — a construction failure here reflects a
    /// host/environment condition that will not change between calls within
    /// the same process.
    pub fn shared() -> Result<&'static PluginLoader, String> {
        SHARED_LOADER
            .get_or_init(|| PluginLoader::new().map_err(|e| e.to_string()))
            .as_ref()
            .map_err(|e| e.clone())
    }

    /// Steps shared by [`load_plugin`](Self::load_plugin) and
    /// [`describe_plugin`](Self::describe_plugin): read the file, compile it
    /// to a component, build a linker with the full WASIp2 + HTTP surface,
    /// pre-instantiate, and validate that the `aerini-node` world is
    /// exported. Extracted so the two call paths — one that goes on to leak
    /// `'static` strings and register a live `Node`, one that doesn't —
    /// can't drift apart on the compile/link logic itself.
    fn compile_and_link(&self, path: &Path) -> Result<wit::AeriniNodePre<PluginState>, PluginLoadError> {
        // Steps 1-2: read + compile — or reuse a cached `Component` for this
        // exact path if its (mtime, len) fingerprint matches what's cached.
        // `std::fs::metadata` (not `std::fs::read`) is the first fallible
        // call so a missing/unreadable file still produces `Io`, not
        // `WasmCompile` — matching the pre-cache error classification the
        // existing tests assert on. A changed fingerprint (file replaced,
        // e.g. via remove+reinstall under the same filename) forces a fresh
        // compile rather than serving stale bytes.
        let meta = std::fs::metadata(path)?;
        let fingerprint = (meta.modified().ok(), meta.len());

        let cached = self
            .component_cache
            .lock()
            .expect("component cache mutex poisoned")
            .get(path)
            .filter(|entry| entry.fingerprint == fingerprint)
            .map(|entry| entry.component.clone());

        let component = match cached {
            Some(c) => c,
            None => {
                // Step 1: read — produces Io error (not WasmCompile) for missing files.
                let bytes = std::fs::read(path)?;

                // Step 2: compile. Accepts WAT text or WASM binary — wasmtime detects by magic.
                let component = wasmtime::component::Component::new(&self.engine, &bytes)
                    .map_err(|e| PluginLoadError::WasmCompile(e.to_string()))?;

                self.compile_count.fetch_add(1, std::sync::atomic::Ordering::SeqCst);

                self.component_cache
                    .lock()
                    .expect("component cache mutex poisoned")
                    .insert(path.to_path_buf(), CachedComponent { fingerprint, component: component.clone() });

                component
            }
        };

        // Step 3: linker + pre-instantiation.
        //
        // Two separate calls are required:
        // (a) `wasmtime_wasi::p2::add_to_linker_sync` — satisfies all `wasi:cli/command`
        //     imports (filesystem, random, clocks, stdio) that `wasm32-wasip2` binaries
        //     unconditionally import via Rust's standard library.
        // (b) `wasmtime_wasi_http::p2::add_only_http_to_linker_sync` — adds only the
        //     `wasi:http/outgoing-handler` interface without duplicating the WASI
        //     interfaces already registered in (a).
        //
        // Using just `wasmtime_wasi_http::p2::add_to_linker_sync` (the proxy world bundle)
        // instead of (a)+(b) would omit `wasi:filesystem`, `wasi:random`, etc., causing
        // `linker.instantiate_pre` to fail for every standard `wasm32-wasip2` plugin.
        let mut linker = wasmtime::component::Linker::<PluginState>::new(&self.engine);
        wasmtime_wasi::p2::add_to_linker_sync(&mut linker)
            .map_err(|e| PluginLoadError::WasmLink(e.to_string()))?;
        wasmtime_wasi_http::p2::add_only_http_to_linker_sync(&mut linker)
            .map_err(|e| PluginLoadError::WasmLink(e.to_string()))?;

        let instance_pre = linker.instantiate_pre(&component)
            .map_err(|e| PluginLoadError::WasmLink(e.to_string()))?;

        // Step 4: validate the `aerini-node` world export exists.
        wit::AeriniNodePre::new(instance_pre).map_err(|_| PluginLoadError::MissingInterface)
    }

    /// Load a single WASM plugin from `path`.
    ///
    /// Steps:
    /// 1. Read the file (→ [`PluginLoadError::Io`] on failure).
    /// 2. Compile to a component (→ [`PluginLoadError::WasmCompile`] on failure).
    /// 3. Build a linker with full WASIp2 + HTTP and pre-instantiate
    ///    (→ [`PluginLoadError::WasmLink`] on failure).
    /// 4. Validate that the component exports the `aerini-node` world
    ///    (→ [`PluginLoadError::MissingInterface`] if absent).
    /// 5. Call `describe()` once to populate the [`NodeDescriptor`](crate::node::NodeDescriptor).
    ///
    /// The `describe()` result is cached in [`WasmPluginNode`] for the lifetime
    /// of the process — it is never called again after load time.
    pub fn load_plugin(&self, path: &Path) -> Result<Arc<dyn Node>, PluginLoadError> {
        // Steps 1-4: read, compile, link, pre-instantiate, validate world export.
        let pre = self.compile_and_link(path)?;

        // Step 5: call describe() once to get node metadata.
        let mut store = make_store(&self.engine, make_plugin_state());

        let bindings = pre.instantiate(&mut store)
            .map_err(|e| PluginLoadError::WasmLink(e.to_string()))?;

        let descriptor = bindings
            .aerini_plugin_node()
            .call_describe(&mut store)
            .map_err(|e| PluginLoadError::WasmLink(e.to_string()))?;

        // Leak type_id and display_name once per plugin load — bounded intentional leak:
        // plugins are loaded once at process start and live for the process lifetime.
        // Only safe because this method is reached once per plugin per process (via
        // `load_plugins_from_dir`, called from `load_plugins` through `shared()`) —
        // a caller needing repeatable metadata lookups must use `describe_plugin`
        // instead, which runs the identical steps but leaks nothing.
        let type_id: &'static str = Box::leak(descriptor.type_id.into_boxed_str());
        let display_name: &'static str = Box::leak(descriptor.display_name.into_boxed_str());

        let node_type = category_to_node_type(&descriptor.category, type_id);

        // JSON Schema strings from the plugin — fall back to empty schema on parse failure.
        let input_schema: Value = serde_json::from_str(&descriptor.input_schema)
            .unwrap_or_else(|_| Value::Object(serde_json::Map::new()));
        let output_schema: Value = serde_json::from_str(&descriptor.output_schema)
            .unwrap_or_else(|_| Value::Object(serde_json::Map::new()));

        Ok(Arc::new(WasmPluginNode {
            engine: self.engine.clone(),
            pre,
            type_id,
            display_name,
            node_type,
            input_schema,
            output_schema,
        }))
    }

    /// Returns `type_id`/`display_name`/`node_type` for the plugin at `path`
    /// without registering it as a live [`Node`] and without leaking any
    /// memory — every string in the returned [`PluginDescriptor`] is owned.
    ///
    /// Runs the identical compile/link/describe steps as
    /// [`load_plugin`](Self::load_plugin) (steps 1-5 of that method's own
    /// doc comment), but never calls [`Box::leak`] and never constructs a
    /// [`WasmPluginNode`] — the compiled component, linker, and store are
    /// all dropped when this method returns. Safe to call as many times as
    /// a caller needs, unlike `load_plugin`, whose leak is only bounded when
    /// called once per plugin per process.
    pub fn describe_plugin(&self, path: &Path) -> Result<PluginDescriptor, PluginLoadError> {
        let pre = self.compile_and_link(path)?;

        let mut store = make_store(&self.engine, make_plugin_state());

        let bindings = pre.instantiate(&mut store)
            .map_err(|e| PluginLoadError::WasmLink(e.to_string()))?;

        let descriptor = bindings
            .aerini_plugin_node()
            .call_describe(&mut store)
            .map_err(|e| PluginLoadError::WasmLink(e.to_string()))?;

        let node_type = category_to_node_type(&descriptor.category, &descriptor.type_id);

        Ok(PluginDescriptor {
            type_id: descriptor.type_id,
            display_name: descriptor.display_name,
            node_type,
        })
    }

    /// Load all `.wasm` files from `dir` as plugins.
    ///
    /// Files that fail to load are logged as warnings and skipped — they do not
    /// prevent other plugins from loading or crash the process.
    ///
    /// Returns an empty `Vec` if the directory cannot be read.
    pub fn load_plugins_from_dir(&self, dir: &Path) -> Vec<Arc<dyn Node>> {
        let entries = match std::fs::read_dir(dir) {
            Ok(e) => e,
            Err(err) => {
                tracing::warn!(
                    "plugin_loader: cannot read plugin directory {}: {}",
                    dir.display(),
                    err
                );
                return vec![];
            }
        };

        let mut nodes: Vec<Arc<dyn Node>> = Vec::new();

        for entry in entries {
            let entry = match entry {
                Ok(e) => e,
                Err(err) => {
                    tracing::warn!("plugin_loader: error reading directory entry: {}", err);
                    continue;
                }
            };

            let path = entry.path();

            if path.extension().and_then(|e| e.to_str()) != Some("wasm") {
                continue;
            }

            match self.load_plugin(&path) {
                Ok(node) => {
                    tracing::info!(
                        "plugin_loader: loaded plugin '{}' from {}",
                        node.type_id(),
                        path.display()
                    );
                    nodes.push(node);
                }
                Err(err) => {
                    tracing::warn!(
                        "plugin_loader: skipping {}: {}",
                        path.display(),
                        err
                    );
                }
            }
        }

        nodes
    }
}

// ── WasmPluginNode ────────────────────────────────────────────────────────────

/// A node implementation backed by a WASM component.
///
/// Registered in [`NodeRegistry`] identically to built-in nodes and appears in the
/// UI palette via the cached [`NodeDescriptor`](crate::node::NodeDescriptor) with
/// no frontend changes required.
///
/// # Execution isolation
///
/// Each `execute()` call creates a fresh [`wasmtime::Store<PluginState>`] from the
/// shared engine and the pre-compiled [`wit::AeriniNodePre`]. The `Store` is created
/// and consumed entirely within a `spawn_blocking` closure — it never crosses an
/// `await` point and is dropped at the end of the call.
///
/// # Input serialization
///
/// The executor provides `input.input` as a merged JSON object (config + resolved
/// credentials). This is serialized to `Vec<wit::Param>` key-value pairs and passed
/// to the plugin as `NodeInput.params`. `credentials` is left empty because the
/// executor has already resolved and merged credential values into `input.input`.
///
/// # Output deserialization
///
/// `NodeOutput.data` is a JSON string. On success it is parsed to `serde_json::Value`;
/// a parse failure is treated as a genuine, logged node failure (`wasm_invalid_output`),
/// not silently substituted with empty output.
///
/// # Static string fields
///
/// `type_id` and `display_name` are [`Box::leak`]ed once at load time. This is a
/// bounded, intentional leak: plugins are loaded once at process start and never
/// unloaded.
pub struct WasmPluginNode {
    /// Shared engine — cheap to clone (internally ref-counted).
    engine: Engine,
    /// Pre-compiled component with import-satisfaction already verified.
    /// `Clone + Send + Sync`. Re-instantiated per `execute()` call.
    pre: wit::AeriniNodePre<PluginState>,
    type_id: &'static str,
    display_name: &'static str,
    node_type: NodeType,
    input_schema: Value,
    output_schema: Value,
}

#[async_trait]
impl Node for WasmPluginNode {
    fn type_id(&self) -> &'static str {
        self.type_id
    }

    fn display_name(&self) -> &'static str {
        self.display_name
    }

    fn node_type(&self) -> NodeType {
        self.node_type.clone()
    }

    fn version(&self) -> &'static str {
        // WASM plugins do not expose a version via WIT. Plugins may embed their
        // version in type_id (e.g. "com.example.my-node@1.2.0") if needed.
        "1.0.0"
    }

    fn is_plugin(&self) -> bool {
        true
    }

    fn input_schema(&self) -> Value {
        self.input_schema.clone()
    }

    fn output_schema(&self) -> Value {
        self.output_schema.clone()
    }

    /// Execute the plugin node.
    ///
    /// Runs synchronous Wasmtime instantiation + function call in
    /// `tokio::task::spawn_blocking` so the async executor is never blocked.
    /// A fresh `Store` is created per call for full execution isolation.
    async fn execute(&self, input: NodeInput) -> NodeOutput {
        let engine = self.engine.clone();
        let pre = self.pre.clone();
        let wit_input = engine_input_to_wit(&input);

        let result = tokio::task::spawn_blocking(move || {
            let mut store = make_store(&engine, make_plugin_state());

            let bindings = pre.instantiate(&mut store).map_err(|e| e.to_string())?;

            bindings
                .aerini_plugin_node()
                .call_execute(&mut store, &wit_input)
                .map_err(|e| e.to_string())
        })
        .await;

        match result {
            Ok(Ok(out)) => wit_output_to_engine(out),
            // Traps are unrecoverable: retrying the same input produces the same trap.
            Ok(Err(trap_msg)) => NodeOutput::failure(NodeError::unrecoverable(
                "wasm_trap",
                format!("plugin execution trapped: {trap_msg}"),
            )),
            Err(join_err) => NodeOutput::failure(NodeError::unrecoverable(
                "wasm_panic",
                format!("plugin task panicked: {join_err}"),
            )),
        }
    }
}

// ── Input / output conversion ─────────────────────────────────────────────────

/// Flatten the merged JSON input into a `Vec<Param>` for the WIT interface.
///
/// The executor merges config and resolved credentials into `input.input` as a
/// JSON object. Each top-level key becomes a `Param`. Non-string values are
/// serialized to their JSON text representation (e.g. numbers, booleans, objects).
fn engine_input_to_wit(input: &NodeInput) -> wit::NodeInput {
    let params = match &input.input {
        Value::Object(map) => map
            .iter()
            .map(|(k, v)| wit::Param {
                key: k.clone(),
                value: match v {
                    Value::String(s) => s.clone(),
                    other => other.to_string(),
                },
            })
            .collect(),
        _ => vec![],
    };

    wit::NodeInput {
        params,
        credentials: vec![], // already merged into input.input by the executor
    }
}

/// Convert a WIT `NodeOutput` record to the engine's [`NodeOutput`].
fn wit_output_to_engine(out: wit::NodeOutput) -> NodeOutput {
    if out.success {
        match serde_json::from_str::<Value>(&out.data) {
            Ok(value) => NodeOutput::success(value),
            Err(parse_err) => {
                // A plugin that reports success but returns non-JSON `data` was
                // previously papered over as an empty `{}` object with no error
                // and no log line — indistinguishable from a plugin that legitimately
                // returns no data. Surface it as a real, logged failure instead.
                let preview: String = out.data.chars().take(INVALID_OUTPUT_LOG_PREVIEW_CHARS).collect();
                tracing::error!(
                    "plugin_loader: plugin reported success but `data` is not valid JSON: {} (data preview: {:?})",
                    parse_err,
                    preview
                );
                NodeOutput::failure(NodeError::unrecoverable(
                    "wasm_invalid_output",
                    format!(
                        "plugin reported success but its output was not valid JSON: {parse_err}"
                    ),
                ))
            }
        }
    } else {
        NodeOutput::failure(NodeError {
            code: out.error_code,
            message: out.error_message,
            recoverable: out.recoverable,
        })
    }
}

// ── Public API ────────────────────────────────────────────────────────────────

/// Load all WASM plugins from `plugin_dir` and register them in `registry`.
///
/// Constructs a [`PluginLoader`] (and a Wasmtime engine) internally.
/// Called by `aerini-server` and `src-tauri` after [`crate::nodes::register_builtins`].
/// Seals the built-in namespace before registering any plugins so that a plugin
/// whose `type_id` collides with a built-in is rejected rather than silently replacing it.
///
/// If the Wasmtime engine fails to initialise, an error is logged and the function
/// returns without registering any plugins — the process continues normally.
pub fn load_plugins(registry: &mut NodeRegistry, plugin_dir: &Path) {
    // Seal the built-in namespace before loading any plugins so that a plugin
    // cannot shadow a built-in node type (e.g. "http_request", "shell_exec").
    registry.seal_builtins();

    // SECURITY NOTICE: WASM plugins' outbound HTTP (wasi:http/outgoing-handler) is
    // checked against the same SSRF policy as the Database and HTTP nodes before
    // any request is sent (see `check_plugin_request_ssrf`) — RFC 1918, loopback,
    // link-local, and cloud metadata addresses are rejected. That check has the
    // same DNS-rebinding TOCTOU gap documented on `nodes::util::check_host_ssrf`,
    // and a plugin still runs with the full trust of whatever else this process
    // can reach once a request clears it. Treat the plugin directory as a trust
    // boundary equivalent to running arbitrary native code, and enforce
    // network-level egress filtering as defence-in-depth for the TOCTOU gap in
    // server/API deployments.
    tracing::warn!(
        "plugin_loader: loading WASM plugins from '{}'. Outbound HTTP is SSRF-filtered (RFC1918/loopback/link-local/cloud-metadata blocked), but only load plugins from trusted sources — a DNS-rebinding TOCTOU gap remains; enforce network-level egress filtering as defence-in-depth.",
        plugin_dir.display()
    );

    let loader = match PluginLoader::shared() {
        Ok(l) => l,
        Err(e) => {
            tracing::error!(
                "plugin_loader: failed to initialise Wasmtime engine: {}",
                e
            );
            return;
        }
    };

    let nodes = loader.load_plugins_from_dir(plugin_dir);
    let mut loaded = 0usize;
    let mut rejected = 0usize;
    for node in nodes {
        match registry.register_plugin(node) {
            Ok(()) => loaded += 1,
            Err(_) => rejected += 1,   // warning already emitted inside register_plugin
        }
    }

    if rejected > 0 {
        tracing::warn!(
            "plugin_loader: {} plugin node(s) rejected (built-in type_id collision) from {}",
            rejected,
            plugin_dir.display()
        );
    }
    tracing::info!(
        "plugin_loader: loaded {} plugin node(s) from {}",
        loaded,
        plugin_dir.display()
    );
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn loader() -> PluginLoader {
        PluginLoader::new().expect("Wasmtime engine init failed in test")
    }

    /// Non-existent path must return `PluginLoadError::Io`.
    #[test]
    fn load_plugin_nonexistent_file_returns_io_error() {
        let l = loader();
        let result = l.load_plugin(Path::new("/nonexistent/path/to/plugin.wasm"));
        assert!(result.is_err(), "expected Io error, got Ok");
        let err = result.err().unwrap();
        assert!(
            matches!(err, PluginLoadError::Io(_)),
            "expected Io, got: {err:?}"
        );
    }

    /// A valid WASM component that does NOT export the `aerini-node` world must
    /// return `PluginLoadError::MissingInterface`.
    ///
    /// Uses `(component)` — the smallest valid Component Model component. It has no
    /// exports and no imports, so `linker.instantiate_pre` succeeds (no unsatisfied
    /// imports) but `AeriniNodePre::new` fails (no `aerini:plugin/node` export).
    #[test]
    fn load_plugin_empty_component_returns_missing_interface() {
        let l = loader();

        let mut tmp = tempfile::NamedTempFile::new().expect("tempfile create failed");
        tmp.write_all(b"(component)").expect("tempfile write failed");
        tmp.flush().expect("tempfile flush failed");

        let result = l.load_plugin(tmp.path());
        assert!(result.is_err(), "expected MissingInterface error, got Ok");
        let err = result.err().unwrap();
        assert!(
            matches!(err, PluginLoadError::MissingInterface),
            "expected MissingInterface, got: {err:?}"
        );
    }

    /// `describe_plugin` must classify errors identically to `load_plugin`
    /// for the same non-existent-path input — the non-leaking path must not
    /// silently swallow or misclassify an error `load_plugin` already
    /// handles correctly.
    #[test]
    fn describe_plugin_nonexistent_file_returns_io_error() {
        let l = loader();
        let result = l.describe_plugin(Path::new("/nonexistent/path/to/plugin.wasm"));
        assert!(result.is_err(), "expected Io error, got Ok");
        let err = result.err().unwrap();
        assert!(
            matches!(err, PluginLoadError::Io(_)),
            "expected Io, got: {err:?}"
        );
    }

    /// `describe_plugin` must classify a world-less component identically to
    /// `load_plugin` (same mechanism as `load_plugin_empty_component_returns_missing_interface`
    /// above — see that test's doc comment for why `(component)` triggers this path).
    #[test]
    fn describe_plugin_empty_component_returns_missing_interface() {
        let l = loader();

        let mut tmp = tempfile::NamedTempFile::new().expect("tempfile create failed");
        tmp.write_all(b"(component)").expect("tempfile write failed");
        tmp.flush().expect("tempfile flush failed");

        let result = l.describe_plugin(tmp.path());
        assert!(result.is_err(), "expected MissingInterface error, got Ok");
        let err = result.err().unwrap();
        assert!(
            matches!(err, PluginLoadError::MissingInterface),
            "expected MissingInterface, got: {err:?}"
        );
    }

    /// `PluginLoader::shared()` must return the same
    /// process-wide instance on every call, not construct a fresh `Engine` +
    /// epoch-ticker thread each time (each such construction is a leak if
    /// nothing ever tears it down — the exact failure mode a call site using
    /// its own `PluginLoader::new()` instead of `shared()` would hit).
    /// Pointer equality on the returned `&'static PluginLoader` is a direct
    /// proxy for "no second construction happened": `OnceLock::get_or_init`
    /// only ever runs its initializer once, so two `Ok` results can only
    /// share an address if they came from the same underlying
    /// `PluginLoader`.
    #[test]
    fn shared_returns_same_instance_across_repeated_calls() {
        let a = PluginLoader::shared().expect("shared() should succeed on a normal host");
        let b = PluginLoader::shared().expect("shared() should succeed on a normal host");
        let c = PluginLoader::shared().expect("shared() should succeed on a normal host");
        assert!(
            std::ptr::eq(a, b) && std::ptr::eq(b, c),
            "shared() must return the same PluginLoader on every call, not construct a new one"
        );
    }

    /// `describe_plugin` must agree with `load_plugin` on the metadata it
    /// extracts for the same input — this only has an error path to compare
    /// in this test module (no valid `aerini-node`-exporting fixture is
    /// available without a real compiled plugin), so this asserts the two
    /// paths at least agree on failure classification for a second distinct
    /// error shape (`WasmCompile`, via a byte string that is neither valid
    /// WAT text nor a valid WASM binary).
    #[test]
    fn describe_plugin_and_load_plugin_agree_on_invalid_bytes() {
        let l = loader();

        let mut tmp = tempfile::NamedTempFile::new().expect("tempfile create failed");
        tmp.write_all(b"not a wasm module or wat text").expect("tempfile write failed");
        tmp.flush().expect("tempfile flush failed");

        let load_err = l.load_plugin(tmp.path()).err().expect("load_plugin should fail");
        let describe_err = l.describe_plugin(tmp.path()).err().expect("describe_plugin should fail");

        assert!(matches!(load_err, PluginLoadError::WasmCompile(_)));
        assert!(matches!(describe_err, PluginLoadError::WasmCompile(_)));
    }

    /// repeated `describe_plugin` calls against the same, unchanged file must
    /// compile the `.wasm` bytes exactly once, not on every call. Uses a
    /// per-instance compile counter (see `compile_count`) rather than
    /// timing, so this can't be flaky.
    #[test]
    fn describe_plugin_reuses_cached_component_for_unchanged_file() {
        let l = loader();

        let mut tmp = tempfile::NamedTempFile::new().expect("tempfile create failed");
        tmp.write_all(b"(component)").expect("tempfile write failed");
        tmp.flush().expect("tempfile flush failed");

        for _ in 0..3 {
            // Every call returns MissingInterface (no export) — only the
            // compile *count*, not the result, is under test here.
            let _ = l.describe_plugin(tmp.path());
        }

        assert_eq!(
            l.compile_count(),
            1,
            "expected exactly one real compile across three describe_plugin calls on an unchanged file"
        );
    }

    /// Companion to the above: if the file at the same path actually
    /// changes (different length — covers a plugin removed and a
    /// different one reinstalled under the same filename), the cache must
    /// not serve stale bytes — a fresh compile is required.
    #[test]
    fn describe_plugin_recompiles_when_file_content_changes() {
        let l = loader();

        let mut tmp = tempfile::NamedTempFile::new().expect("tempfile create failed");
        tmp.write_all(b"(component)").expect("tempfile write failed");
        tmp.flush().expect("tempfile flush failed");

        let _ = l.describe_plugin(tmp.path());
        assert_eq!(l.compile_count(), 1);

        // Truncate and rewrite with different (longer) content so the
        // (mtime, len) fingerprint changes regardless of filesystem mtime
        // resolution.
        use std::io::{Seek, SeekFrom};
        tmp.as_file_mut().set_len(0).expect("truncate failed");
        tmp.as_file_mut().seek(SeekFrom::Start(0)).expect("seek failed");
        tmp.write_all(b"(component (core module (memory 1) (data (i32.const 100) \"abcd\")))")
            .expect("tempfile rewrite failed");
        tmp.flush().expect("tempfile flush failed");

        let _ = l.describe_plugin(tmp.path());
        assert_eq!(
            l.compile_count(),
            2,
            "file content/length changed at the same path — must recompile, not reuse the stale cached Component"
        );
    }
}
